### ISSUE TITLE
0.6.1 login youtube failure

### ISSUE THREAD

**Issue by Roppieee** [matjaz/homey-youtube#14]
Just installed the 0.6.1 version and tried to login . When I push the "Settings.LoginText" I got the following error screen. Any thoughts how to resolve this?

![image](https://cloud.githubusercontent.com/assets/24712933/25148465/5116b3b6-247b-11e7-8010-cc8d8546ae6a.png)

**Comment by matjaz** [comment]
You need OAuth `CLIENT_ID` and `CLIENT_SECRET` in `env.json`. You can obtain it from [Google console](https://console.developers.google.com/apis/credentials).
Once approved it will just work from app store.
