### ISSUE TITLE
0.6.1 login error

### ISSUE THREAD

**Issue by Roppieee** [matjaz/homey-youtube#15]
Hi,

Just installed 0.6.1 but I'm getting an error when trying to login. See screenshots. Any thoughts how to resolve this?

Thanks

![image](https://cloud.githubusercontent.com/assets/24712933/25150873/c1ffdfaa-2483-11e7-856b-60a745fd78ba.png)

**Comment by matjaz** [comment]
duplicate https://github.com/matjaz/homey-youtube/issues/14
