### ISSUE TITLE
Problem switching/stopping playlists

### ISSUE THREAD

**Issue by gkroone** [matjaz/homey-youtube#3]
As per examples found on the forum, I have created a flow on my homey to play a new URL to my Chromecast on Youtube Media Changed, and this works quite well. I am however experiencing issues when starting a new playlist. The new playlist starts playikng just fine, however during playback of the new playlist, after some time, a video from the previous playlist starts to play again.

My flows to start a youtube playlist do include the command to first stop the current playlist and start the new one with some delay, however It looks like the the command to stop the current playlist doesn't work. the only way I found to stop all previous playlists is to reboot my homey.

**Comment by matjaz** [comment]
Should be fixed in 0.3.1 / 57ddcadc
Pending store approval / can test it from github.

**Comment by gkroone** [comment]
It's been quite a while but still the store only shows 0.3.0 and I have no idea how to go about instlling an app directly from Gitub. can you refer any reading material on this, or some pointer to start on that?

**Comment by matjaz** [comment]
#0.3.1 has just been published to [app store](https://apps.athom.com/app/com.youtube).

For installing apps from code you need `athom-cli`
see https://developers.athom.com/library/getting-started/ to install run `athom project --install`
