### ISSUE TITLE
Returned items invariably return track duration

### ISSUE THREAD

**Issue by TheMSB** [matjaz/homey-youtube#4]
Not all returned items return a track duration > 0.
In order to remain compatible in the future, this will need to be addressed.

Would you be able to manage this fix in the near future or would you like me to work on a PR?

**Comment by matjaz** [comment]
I was already working something on this.
Idea is to player notify YouTube app when media status changes.
https://github.com/matjaz/homey-youtube/commits/chromecast
And status notify for Chromecast app https://github.com/matjaz/com.google.chromecast/commits/realtime
But I haven't managed to get notifications working.

Please describe what solution do you propose and we can work something out. PRs are always welcome. :)

**Comment by TheMSB** [comment]
As far as I am aware it is possible to retrieve the duration of youtube tracks with a second API call.
I would prefer it if you would fetch this track duration and insert it into your track object before offering it up to the media manager. Do you think this is possible?

**Comment by matjaz** [comment]
That's what `media.getVideo` is doing. https://github.com/matjaz/homey-youtube/blob/master/lib/playlist.js#L106
Which YT API call do you have in mind?

**Comment by TheMSB** [comment]
I've been going over the source code and my reasoning about the code execution is as follows:

Looking at `media.js`
I see 

``` javascript
Homey.manager('media').on('search', function (parsedQuery, callback)
```

Where starting at line 31 you set the track duration to 0 (I assume that is because youtube provides none in the initial call?)

``` javascript
lastResults = result.items.map(function (item) {
        return {
          type: 'track',
          id: item.id.videoId,
          title: item.snippet.title,
          album: item.snippet.description,
          artist: item.snippet.channelTitle,
          artwork: item.snippet.thumbnails.default.url,
          duration: 0,
          confidence: 0.5
        }
      })
```

Then I look at the on play event
`Homey.manager('media').on('play', exports.playVideoId)`

And reference the playVideoId method where I see that on line  78 you call getVideo.
GetVideo does nothing to modify the duration of the track before the callback passes it to setTrack.

``` javascript
exports.playVideoId = function (videoId, callback) {
  exports.getVideo(videoId, function (err, result) {
    if (err) {
      callback(err)
      return
    }
    var item = result.items[0]
    // Homey.log('media play item', item)
    if (item) {
      exports.setTrack(item, callback)
    } else {
      callback(null, false)
    }
  })
}
```

setTrack does contain a check to calculate the item duration but this seems moot as the duration value is set to 0 and does not seem to get changed.
It is then passed onto the Homey media manager while the duration value is still 0.

``` javascript
exports.setTrack = function (item, callback) {
  var id = item.id.videoId || item.id
  youtubemp3.getDownloadUrl(id, function (err, url) {
    if (err) {
      callback(err)
      return
    }
    var duration = 0
    if (item.contentDetails && item.contentDetails.duration) {
      duration = util.parsePeriod(item.contentDetails.duration)
    }
    Homey.manager('media').setTrack({
      id: id,
      title: item.snippet.title,
      album: item.snippet.description,
      artist: item.snippet.channelTitle,
      artwork: item.snippet.thumbnails.default.url,
      duration: duration,
      stream_url: url
    })
    callback(null, true)
  })
}
```

Unless I am mistaken and the app itself intercepts the item somewhere and modifies the value I would suggest modifying the value in a similar manner as in `Playlists.js` before setTrack is called.

**Comment by matjaz** [comment]
`media.js` is for Homey's media manager. Afaik media manager "track" duration is only showed on media player songs list.
This is not related to playlist. So about which duration are you talking about?

**Comment by TheMSB** [comment]
I am talking about the duration of the Youtube track that is being offered up to the Homey media manager. As it stands the media manager receives tracks from the youtube app with a duration of 0.

In the future the media manager will become a much larger part of the homey client and the current behaviour will not be compatible with a future version.

The Homey media manger will support things like playlists natively (soon (tm)) and in order to ensure correct playback it is preferable that the youtube app returns a valid track duration along with the track object at the time it is offered up to the Homey media manager.

**Comment by matjaz** [comment]
OK, so if I understand correctly track duration will have to be > 0. Which in YouTube case requires n+1 (items) requests for media manager on search handler.

**Comment by TheMSB** [comment]
Yeah basically that, also if for some reason the track does not have a duration (Youtube livestreams for example) then returning a duration of false is preferred over a duration of 0.

**Comment by matjaz** [comment]
ok. If you have time please make PR and I'll gladly merge it.
for duration I think `undefined` is more appropriate if duration is unknown - not defined.

**Comment by TheMSB** [comment]
I figured out the actual problem wasn't that the metadata wasn't included, just that it zeroed out because of rounding. The Media Manager actually uses milliseconds so most track durations would just round to 0. I will make a PR with a hot fix that should ensure compatibility.

**Comment by matjaz** [comment]
Hmm interesting. milliseconds for duration is very precise. Thanks for the help. :)
