### ISSUE TITLE
daily limit exceeded

### ISSUE THREAD

**Issue by bvdbos** [matjaz/homey-youtube#8]
with 0.5.2 on FW1.1.2:
![yt-search](https://cloud.githubusercontent.com/assets/1064079/21748467/3a31bd1a-d586-11e6-930c-0f416d651789.png)

Did you already have a version where you can put in your own api-key? But I suspect something else is wrong to be honest...

**Comment by bvdbos** [comment]
Coincidence I guess but it works now... Daily limit reset I presume... Still: apparently you're hitting limits so I think it's wise to have users enter their own API-key...

**Comment by matjaz** [comment]
resolved in https://github.com/matjaz/homey-youtube/commit/a914a5be56bb722382137741eb6c427309a14094.
